### ISSUE TITLE
RxJava+Ormlite?

### ISSUE THREAD

**Issue by 4gus71n** [mohsenoid/marvel#3]
Hi, really nice App architecture. I've a question, why didn't you wrap the database related operations within a rx.Observable?

I mean, for example in the SearchFragment you called the Presenter's loadCharactersCachedData() method, which later calls the DatabaseHelper's selectAllCharacters() method, which runs on the UI thread, should that kind of operations run on a background thread wrapped inside a rx.Observable?

Same thing with the Presenter's doSearch() method, in that case you wrapped the operation in a rx.Observable but you made it run over AndroidScheduler.mainThread(), shouldn't run over some other background thread such as Scheduler.io()?

**Comment by mohsenoid** [comment]
Hi,
Please take a look to other branches, there are so many changes there, but I really get busy with my new position and have no time to improve this sample, you can fork this project and add your own improvement and send a pull request whenever you want. ;)
